Feature/uri variables2
Interactions-HSG/wot-td-java pull request #71
Opened 2021-12-13 20:56 UTC by JeremyLemee

2021-12-13 20:58 UTC, danaivach commented
Tested with XArm and PhantomX TDs.

2021-12-14 10:50 UTC, andreiciortea requested changes
Thanks for this work, @JeremyLemee! Please see the detailed comments, once these are fixed we can merge the PR.

2021-12-14 10:50 UTC, andreiciortea commented on src/main/java/ch/unisg/ics/interactions/wot/td/clients/TDHttpRequest.java
> +
Blank lines are not necessary here

2021-12-14 10:50 UTC, andreiciortea commented on src/main/java/ch/unisg/ics/interactions/wot/td/clients/UriTemplate.java
> +public final class UriTemplate {
This is not very OO. Why not create a regular object UriTemplate instead of using only static methods?

2021-12-14 10:50 UTC, andreiciortea commented on src/main/java/ch/unisg/ics/interactions/wot/td/clients/UriTemplate.java
> +      else if (path.charAt(i)=='}'){
Please see the Google Java Code Style for braces: https://google.github.io/styleguide/javaguide.html#s4.1-braces

2021-12-14 10:50 UTC, andreiciortea commented on src/main/java/ch/unisg/ics/interactions/wot/td/clients/UriTemplate.java
> +
One blank line should be removed

2021-12-14 10:50 UTC, andreiciortea commented on src/main/java/ch/unisg/ics/interactions/wot/td/clients/UriTemplate.java
> +
These blank lines should be removed, see Google Java Style Guide for vertical spacing: https://google.github.io/styleguide/javaguide.html#s4.6-whitespace

2021-12-14 10:50 UTC, andreiciortea commented on src/main/java/ch/unisg/ics/interactions/wot/td/clients/UriTemplate.java
> +        s = s +"}";
Inconsistent use of whitespaces around operators, please review. This should be `s = s + "}";`

2021-12-14 10:50 UTC, andreiciortea commented on src/main/java/ch/unisg/ics/interactions/wot/td/clients/UriTemplate.java
> +
Blank line not necessary

2021-12-14 11:00 UTC, danaivach commented
@JeremyLemee This is an example test for `TDHttpClientTest`:
```
@Test(expected = IllegalArgumentException.class)
  public void testInvalidStringPathVariable(){
    Map<String, DataSchema> uriVariables = new HashMap<>();
    uriVariables.put("subscriptionId", new IntegerSchema.Builder().build());
    Map<String, Object> parameters = new HashMap<>();
    parameters.put("subscriptionId", 0.5);
    new TDHttpRequest(FORM, TD.invokeAction, uriVariables, parameters);
  }
  
 The test should pass because 0.5 is not an Integer. The test currently does not pass, but instead 0.5 is rounded to be an integer.

2021-12-14 14:36 UTC, merged